config/routes.rb
Scribbler::Application.routes.draw do
  get '/auth/twitter/callback', :to => 'sessions#create', :as => 'callback'
  get '/auth/failure', :to => 'sessions#error', :as => 'failure'
  get '/profile', :to => 'sessions#show', :as => 'show'
  delete '/signout', :to => 'sessions#destroy', :as => 'signout'

  resources :scribbles

  root :to => 'scribbles#index'
end

app/models/country.rb
class Country < ActiveRecord::Base

end

app/models/scribble.rb
class Scribble < ActiveRecord::Base
  serialize :filters, Array
  serialize :params, Hash

  def filter_str
    self.filters && self.filters.join(',')
  end

  def filter_str=(f)
    self.filters = f.split(',').map(&:strip)
  end

  def param_str
    self.params && self.params.to_s
  end

  def param_str=(p)
    if h = Hash[*p.split(',').map(&:strip)]
      self.params = h
    end
  end

  def create_stream
    #twitter = OmniAuth::Strategies::Twitter.new(nil, CONSUMER_KEY, CONSUMER_SECRET)
    consumer = OAuth::Consumer.new(CONSUMER_KEY, CONSUMER_SECRET,
                { :site => "http://stream.twitter.com", :scheme => :header })
    token = OAuth::AccessToken.from_hash(consumer,
      :oauth_token => ACCESS_TOKEN, :oauth_token_secret => ACCESS_SECRET)
    oauth = {
      :consumer_key => CONSUMER_KEY,
      :consumer_secret => CONSUMER_SECRET,
      :access_key => token.token,
      :access_secret => token.secret
    }
    Twitter::JSONStream.connect(
      #:filter => self.filters,
      :filters => self.filters,
      :oauth => oauth,
      :method => 'POST',
      :ssl => true
      #:params => self.params,
    )
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/country_countroller.rb
class ScribblesController < ApplicationController
#@employees = Employee.find(:all)

app/controllers/scribbles_controller.rb
class ScribblesController < ApplicationController
  #before_filter :authorize

  # GET /scribbles
  # GET /scribbles.xml
  def index
    @scribbles = Scribble.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @scribbles }
    end
  end

  # GET /scribbles/1
  # GET /scribbles/1.xml
  def show
    @scribble = Scribble.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @scribble }
    end
  end

  # GET /scribbles/new
  # GET /scribbles/new.xml
  def new
    @scribble = Scribble.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @scribble }
    end
  end

  # GET /scribbles/1/edit
  def edit
    @scribble = Scribble.find(params[:id])
  end

  # POST /scribbles
  # POST /scribbles.xml
  def create
    @scribble = Scribble.new(params[:scribble])

    respond_to do |format|
      if @scribble.save
        format.html { redirect_to(scribbles_path, :notice => 'Scribble was successfully created.') }
        format.xml  { render :xml => @scribble, :status => :created, :location => @scribble }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @scribble.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /scribbles/1
  # PUT /scribbles/1.xml
  def update
    @scribble = Scribble.find(params[:id])

    respond_to do |format|
      if @scribble.update_attributes(params[:scribble])
        format.html {
          if to_boolean(params[:scribble][:streaming])
            path = scribble_path(@scribble)
          else
            path = scribbles_path
          end
          redirect_to(path, :notice => 'Scribble was successfully updated.')
        }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @scribble.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /scribbles/1
  # DELETE /scribbles/1.xml
  def destroy
    @scribble = Scribble.find(params[:id])
    @scribble.destroy

    respond_to do |format|
      format.html { redirect_to(scribbles_url) }
      format.xml  { head :ok }
    end
  end

  protected
  def authorize
    unless session['access_token'] && session['access_secret']
      flash[:notice] = 'Please sign in first'
      redirect_to root_path
    end
  end

  def to_boolean(value)
    ActiveRecord::ConnectionAdapters::Column.value_to_boolean(value)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    session[:access_token] = request.env['omniauth.auth']['credentials']['token']
    session[:access_secret] = request.env['omniauth.auth']['credentials']['secret']
    redirect_to scribbles_path, :notice => "Signed in with Twitter!"
  end

  def show
    if session['access_token'] && session['access_secret']
      redirect_to scribbles_path
    else
      redirect_to failure_path
    end
  end

  def error
    flash[:error] = "Sign in with Twitter failed!"
    redirect_to root_path
  end

  def destroy
    reset_session
    redirect_to root_path, :notice => "Signed out!"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/scribbles_helper.rb
module ScribblesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Scribbler</title>
  <%= stylesheet_link_tag "web-app-theme/base", "web-app-theme/themes/default/style", "web-app-theme/override", :cache => true %>
  <%= javascript_include_tag :defaults, :cache => true %>
  <%= csrf_meta_tag %>
</head>
<body>
  <div id="container">
    <div id="header">
      <h1><a href="/">Scribbler</a></h1>
      <div id="user-navigation">
        <ul class="wat-cf">
          <% if false %>
            <li><a href="#"><%= t("web-app-theme.profile", :default => "Profile") %></a></li>
            <li><a href="#"><%= t("web-app-theme.settings", :default => "Settings") %></a></li>
            <li><a href="/logout" class="logout"><%= t("web-app-theme.logout", :default => "Logout") %></a></li>
          <% end %>
        </ul>
      </div>
      <div id="main-navigation">
        <ul class="wat-cf"></ul>
      </div>
    </div>    
    <div id="wrapper" class="wat-cf">
      <div class="flash">
        <% flash.each do |type, message| -%>
          <div class="message <%= type %>">
            <p><%= message %></p>
          </div>
        <% end -%>
      </div>
      <div id="main">
        <%= yield %>
        <div id="footer">
          <div class="block">
            <p>Copyright &copy; <%= Time.now.year %> Scribbler.</p>
          </div>      
        </div>
      </div>
      <div id="sidebar">
        <%= yield :sidebar %>
      </div>
    </div>    
  </div>
</body>
</html>

app/views/scribbles/_form.html.erb
  <div class="group">
    <%= f.label :filters, t("activerecord.attributes.scribble.filters", :default => "Filters"), :class => :label %>
    <%= f.text_field :filter_str, :class => 'text_field' %>
    <%= f.label :filters, 'Enable Translation', :class => :label %>
    <%= f.check_box :enable_translate %>
    <%= f.label :filters, 'Select Language', :class => :label %>
    <%= f.text_field :select_language, :class => 'text_field' %>

    <span class="description">Comma-separated list of filters</span>
  </div>

<div class="group navform wat-cf">
  <button class="button" type="submit">
    <%= image_tag("web-app-theme/icons/tick.png", :alt => "#{t("web-app-theme.save", :default => "Save")}") %> <%= t("web-app-theme.save", :default => "Save") %>
  </button>
  <span class="text_button_padding"><%= t("web-app-theme.or", :default => "or") %></span>
	<%= link_to t("web-app-theme.cancel", :default => "Cancel"), scribbles_path, :class => "text_button_padding link_button" %>
</div>

app/views/scribbles/_sidebar.html.erb
<div class="block notice">
  <h3>What is this?</h3>
  <div class="content">
    <p>This is a simple starter project for filtering messages from the <a href="http://dev.twitter.com/docs/streaming-api">Twitter Streaming API</a> into a webapp using <a href="http://pusher.com">Pusher</a> for realtime, in-browser updates.</p>
    <p>To try it out, simply create a <a href="<%= new_scribble_path %>">new</a> Scribble and click 'Follow' to see the realtime feed for your tags.</p>
  </div>
</div>
<div class="block">
  <h3>Links</h3>
  <ul class="navigation">
    <li><a href="http://github.com/mgreen/scribbler">Source Code</a></li>
  </ul>
</div>

app/views/scribbles/edit.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to "#{t("web-app-theme.list", :default => "List")}", scribbles_path  %></li>
      <li><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_scribble_path %></li>
      <li class="active"><%= link_to "#{t("web-app-theme.edit", :default => "Edit")}", edit_scribble_path %></li>
    </ul>
  </div>          
  <div class="content">            
    <h2 class="title"><%= t("web-app-theme.edit", :default => "Edit") %> Scribble</h2>
    <div class="inner">
      <%= form_for @scribble, :url => scribble_path(@scribble), :html => { :class => :form } do |f| -%>
        <%= render :partial => "form", :locals => {:f => f} %>
      <% end -%>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>

app/views/scribbles/index.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first active"><%= link_to "#{t("web-app-theme.list", :default => "List")}", scribbles_path  %></li>
      <li><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_scribble_path %></li>
    </ul>
  </div>          
  <div class="content">          
    <h2 class="title"><%= t("web-app-theme.all", :default => "All")  %> Scribbles</h2>
    <div class="inner">
      <table class="table">
        <tr>             
          <th class="first">Filters</th>
                    <th>
            <%= t("activerecord.attributes.scribble.streaming", :default => t("activerecord.labels.streaming", :default => "Streaming")) %>
          </th>
                    <th><%= t("web-app-theme.created_at", :default => "Created at")  %></th>
          <th class="last">&nbsp;</th>
        </tr>
        <% @scribbles.each do |scribble| -%>
        <tr class="<%= cycle("odd", "even") %>">
          <td>
            <%= scribble.filter_str %>
          </td>
          <td>
            <% form_for(scribble, :action => :put, :url => scribble_path(scribble)) do |f| %>
              <%= f.hidden_field :streaming, :value => !scribble.streaming %>
              <%= f.submit(scribble.streaming ? 'Stop' : 'Start') %>
            <% end %>
          </td>
                    <td>
            <%= scribble.created_at %>
          </td>
          <td class="last">
            <% if scribble.streaming %>
              <%= link_to "#{t("web-app-theme.show", :default => "Show")}", scribble_path(scribble) %>
            <% else %>
              <%= link_to "#{t("web-app-theme.edit", :default => "Edit")}", edit_scribble_path(scribble) %> |
              <%= link_to "#{t("web-app-theme.delete", :default => "Delete")}", scribble_path(scribble), :method => :delete, :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}" %>
            <% end %>
          </td>
        </tr>          
        <% end -%>
      </table>
      <div class="actions-bar wat-cf">
        <div class="actions">
        </div>
        
      </div>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>

app/views/scribbles/new.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to "#{t("web-app-theme.list", :default => "List")}", scribbles_path  %></li>
      <li class="active"><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_scribble_path %></li>
    </ul>
  </div>          
  <div class="content">            
    <h2 class="title"><%= t("web-app-theme.new", :default => "New")%>  Scribble</h2>
    <div class="inner">
      <%= form_for :scribble, :url => scribbles_path, :html => { :class => :form } do |f| -%>
        <%= render :partial => "form", :locals => {:f => f} %>
      <% end -%>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>

app/views/scribbles/show.html.erb
<script src="http://js.pusherapp.com/1.9/pusher.min.js" type="text/javascript"></script>
<script type="text/javascript">
  var pusher = new Pusher('<%= Pusher.key %>');
  channel = pusher.subscribe('<%= PUSHER_CHANNEL %>');
  channel.bind('<%= @scribble.id %>', function(data) {
    //window.console.log(data);
    var elem = $('<li style="display:none"/>');
    elem.append('<div class="left"><img class="avatar" src="'
      + data.user.profile_image_url + '"></div>');
    elem.append('<div class="item"><p>' + data.text + '</p></div>');
    elem.append('<div class="clear"></div>');
    $('#streamlist').prepend(elem);
    elem.fadeIn();
  });
</script>

<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to "#{t("web-app-theme.list", :default => "List")}", scribbles_path  %></li>
      <li><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_scribble_path %></li>
      <li class="active"><%= link_to "#{t("web-app-theme.show", :default => "Show")}", scribble_path %></li>
    </ul>
  </div>          
  <div class="content">
    <h2 class="title">Scribbling</h2>
    <div class="inner">

      <p>
      <ul class="list" id="streamlist">
      </ul>
      </p>

      <% if false %>      
        <p>
          <b><%= t("activerecord.attributes.scribble.streaming", :default => t("activerecord.labels.streaming", :default => "Streaming")) %>:</b>
          <%= @scribble.streaming %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.scribble.filters", :default => t("activerecord.labels.filters", :default => "Filters")) %>:</b>
          <%= @scribble.filters %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.scribble.params", :default => t("activerecord.labels.params", :default => "Params")) %>:</b>
          <%= @scribble.params %>
        </p>
      <div class="wat-cf">
        <%= link_to image_tag("web-app-theme/icons/application_edit.png", :alt => "#{t("web-app-theme.edit", :default=> "Edit")}") + " " + t("web-app-theme.edit", :default=> "Edit"), edit_scribble_path(@scribble), :class => "button" %> 
        <%= link_to image_tag("web-app-theme/icons/cross.png", :alt => "#{t("web-app-theme.delete", :default=> "Delete")}") + " " + t("web-app-theme.delete", :default => "Delete"), scribble_path(@scribble), :method => "delete", :class => "button", :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}" %>
      </div>      
    <% end %>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>